---
  .travis.yml:
    hc_secure: "Ca4tYN7ObME9m43G/tHMBwyEJwFp+1eBiLAzAoSiqvVBHewpJ9J3CuEb2Um+VYwQjL5ohbjUeUHnYaVEyonXwgXfcniGbLYLmM+FVbSbzV/BGGOQBdJZY2TSTVMbZPhepPgANbrItrKTBx2CKe46PcubFx1MIAzrplSR6dJG+/A="

